### ISSUE TITLE
Question: Immutability of reliable dictionary results not an issue here?

### ISSUE THREAD

**Issue by rktect** [Azure-Samples/service-fabric-dotnet-data-streaming-websockets#2]
Regarding the [StockService.PurchaseProduct](https://github.com/Azure-Samples/service-fabric-dotnet-data-streaming-websockets/blob/master/src/DataStreaming/StockService/StockService.cs) and AddStock methods, isn't immutability of the product object returned from the lookup an issue in that the same result object is updated and set back into the IReliableDictionary? 

I thought it was necessary to deep copy returned objects before updating properties and setting the dictionary entry again as shown in [this article](https://github.com/Azure/azure-content/blob/master/articles/service-fabric/service-fabric-work-with-reliable-collections.md). 

Just wondering if I'm missing something... Thanks!

**Comment by ms-toddabel** [comment]
Yes you are correct that a deep copy of the object must be completed before assigning updated values. We'll get this fixed up so it doesn't cause confusion. Immutable objects are a great way to prevent this type of error.

**Comment by rktect** [comment]
Thanks for the clarification Todd - appreciate it.
